### ISSUE TITLE
Errors running example playbooks

### ISSUE THREAD

**Issue by shashank-srinivas** [networktocode/netscaler-ansible#22]
I'm attempting to the run example playbooks from: https://github.com/networktocode/netscaler-ansible/blob/88588ed528b1240355e18b6065ab601864db2a37/examples/netscaler_examples.md

Unfortunately, I'm running into the error below. It seems like it can't recognize `netscaler_lb01`. Do I have to assign`netscaler_lb01` an IP address? I didn't see anything in the docs about defining that value.

```
ansible-playbook netscaler_add_server.yml --extra-vars "/vars/example/deploy_full.yml"

PLAY [PLAY 1 - ENSURE ALL SERVER OBJECTS EXIST] ************************************************************************************************

TASK [TASK 1 - ENSURE SERVER OBJECTS ARE DEPLOYED] *********************************************************************************************
fatal: [netscaler_lb01]: FAILED! => {"failed": true, "msg": "'servers' is undefined"}
	to retry, use: --limit @/Users/shassrin/work/src/netscaler-ansible/examples/netscaler_add_server.retry

PLAY RECAP *************************************************************************************************************************************
netscaler_lb01             : ok=0    changed=0    unreachable=0    failed=1
```

Current settings in my `ansible.cfg`:

```
[defaults]

# some basic default values...

inventory      = /etc/ansible/hosts
library        = /Users/shassrin/work/src/
```

I've defined my inventory file to be `/etc/ansible/hosts`. Below are the contents of my `/etc/ansible/hosts`

```
[all:vars]
username=root
password=<REDACTED>

[netscaler]
netscaler_lb01
```

**Comment by jmcgill298** [comment]
`ansible-playbook netscaler_add_server.yml --extra-vars "/vars/example/deploy_full.yml"`

This is missing an **@** in the path

ansible-playbook netscaler_add_server.yml --extra-vars "@./vars/example/deploy_full.yml"

**Comment by shashank-srinivas** [comment]
> ansible-playbook netscaler_add_server.yml --extra-vars "/vars/example/deploy_full.yml"
> 
> This is missing an @ in the path
> 
> ansible-playbook netscaler_add_server.yml --extra-vars "@./vars/example/deploy_full.yml"

I tried that earlier and ran into this:

```
ansible-playbook netscaler_add_server.yml /etc/ansible/hosts --extra-vars "@./vars/example/deploy_full.yml"
ERROR! the file_name '/Users/shassrin/work/src/netscaler-ansible/examples/vars/example/deploy_full.yml' does not exist, or is not readable
```

I've confirmed that `deploy_full.yml` is readable and is located in that directory.

**Comment by jmcgill298** [comment]
It looks like examples is missing the s:

`ansible-playbook netscaler_add_server.yml /etc/ansible/hosts --extra-vars "@./vars/examples/deploy_full.yml"`

**Comment by jmcgill298** [comment]
also, note that the vars files match the playbook names, so I would use "@./vars/examples/add_server.yml" for the add_server playbook

**Comment by shashank-srinivas** [comment]
> also, note that the vars files match the playbook names, so I would use "@./vars/examples/add_server.yml" for the add_server playbook

thanks, that did it. I think there's something going on with the modules? I ran a full traceback and on the `deploy_full.yml` and am running into the error below. I've confirmed that i have the `requests` python package installed.

```
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/z0/5741vj215bj11x19mrx54vhh0000gn/T/ansible_K5Wo8u/ansible_module_netscaler_server.py", line 897, in <module>
    main()
  File "/var/folders/z0/5741vj215bj11x19mrx54vhh0000gn/T/ansible_K5Wo8u/ansible_module_netscaler_server.py", line 788, in main
    session_login = session.login()
  File "/var/folders/z0/5741vj215bj11x19mrx54vhh0000gn/T/ansible_K5Wo8u/ansible_module_netscaler_server.py", line 559, in login
    login = session.post(url, json=body, headers=self.headers, verify=self.verify)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 549, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 504, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='netscaler_lb01', port=443): Max retries exceeded with url: /nitro/v1/config/login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10a514f10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

failed: [netscaler_lb01] (item={u'comment': u'Test Server', u'ip_address': u'10.***.***.**', u'name': u'kp-api-2'}) => {
    "failed": true,
    "item": {
        "comment": "Test Server",
        "ip_address": "10.***.***.**",
        "name": "kp-api-2"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/z0/5741vj215bj11x19mrx54vhh0000gn/T/ansible_K5Wo8u/ansible_module_netscaler_server.py\", line 897, in <module>\n    main()\n  File \"/var/folders/z0/5741vj215bj11x19mrx54vhh0000gn/T/ansible_K5Wo8u/ansible_module_netscaler_server.py\", line 788, in main\n    session_login = session.login()\n  File \"/var/folders/z0/5741vj215bj11x19mrx54vhh0000gn/T/ansible_K5Wo8u/ansible_module_netscaler_server.py\", line 559, in login\n    login = session.post(url, json=body, headers=self.headers, verify=self.verify)\n  File \"/Library/Python/2.7/site-packages/requests/sessions.py\", line 549, in post\n    return self.request('POST', url, data=data, json=json, **kwargs)\n  File \"/Library/Python/2.7/site-packages/requests/sessions.py\", line 502, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/Library/Python/2.7/site-packages/requests/sessions.py\", line 612, in send\n    r = adapter.send(request, **kwargs)\n  File \"/Library/Python/2.7/site-packages/requests/adapters.py\", line 504, in send\n    raise ConnectionError(e, request=request)\nrequests.exceptions.ConnectionError: HTTPSConnectionPool(host='netscaler_lb01', port=443): Max retries exceeded with url: /nitro/v1/config/login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10a514f10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}
	to retry, use: --limit @/Users/shassrin/work/src/netscaler-ansible/examples/netscaler_deploy_full.retry

PLAY RECAP *************************************************************************************************************************************
netscaler_lb01             : ok=0    changed=0    unreachable=0    failed=1

```

I'm curious as to how this actually logs into the netscaler cli to run the necessary commands. Right now I've only given it the user/pass but not the IP of the netscaler.

**Comment by jmcgill298** [comment]
The error reports: `Failed to establish a new connection:` The playbook as it is in the `inventory_hostname` variable from hosts defined under `netscaler` from the inventory file.

**Comment by shashank-srinivas** [comment]
> The error reports: Failed to establish a new connection: The playbook as it is in the inventory_hostname variable from hosts defined under netscaler from the inventory file.

Sorry, I'm a little confused by your reply. Is this what I should have in my `/etc/ansible/hosts` file?

```
[all:vars]
username=root
password=<REDACTED>

[netscaler]
netscaler_lb01
inventory_hostname=16*.**.***.***
```
The example doc found here: https://github.com/networktocode/netscaler-ansible/blob/d99f725bf1c530dde2537ca2bc9239dcc844f264/examples.md doesn't list the inventory_hostname. Also, on that page it lists a playbook and netscaler facts. Do I need to add that stuff to the inventory file? Or should those be created separately? and if so where?

**Comment by jmcgill298** [comment]
In order for that inventory to be useable, netscaler_lb01 would need to be resolvable by the host running Ansible. Here are the docs from Ansible for creating inventory: http://docs.ansible.com/ansible/latest/intro_inventory.html

Please let me know if you need any clarification from the docs.

**Comment by sanket4373** [comment]
@jmcgill298: Went past the earlier error.. As per you suggestion fixed the hostname in the inventory to this

```
[all:vars]
username=root
password=<REDACTED>

[netscaler]
<ip_address_of_ns_appliance>
```
After running it.. Getting sslv3 alert handshake failure.. I am posting the traceback..

```
TASK [TASK 1 - ENSURE SERVER OBJECTS ARE DEPLOYED] ***************************************************************************************************************************************************************************************************************************
task path: /home/kp/netscaler-ansible/examples/netscaler_deploy_full.yml:9
Using module file /home/kp/netscaler-ansible/library/netscaler_server.py
<*.*.*.*> ESTABLISH LOCAL CONNECTION FOR USER: keyprotect
<*.*.*.*> EXEC /bin/sh -c 'echo ~ && sleep 0'
<*.*.*.*> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/kp/.ansible/tmp/ansible-tmp-1502997685.77-49824597265040 `" && echo ansible-tmp-1502997685.77-49824597265040="` echo /home/kp/.ansible/tmp/ansible-tmp-1502997685.77-49824597265040 `" ) && sleep 0'
<*.*.*.*> PUT /tmp/tmpjWMhNa TO /home/kp/.ansible/tmp/ansible-tmp-1502997685.77-49824597265040/netscaler_server.py
<*.*.*.*> EXEC /bin/sh -c 'chmod u+x /home/kp/.ansible/tmp/ansible-tmp-1502997685.77-49824597265040/ /home/kp/.ansible/tmp/ansible-tmp-1502997685.77-49824597265040/netscaler_server.py && sleep 0'
<*.*.*.*> EXEC /bin/sh -c '/usr/bin/python /home/kp/.ansible/tmp/ansible-tmp-1502997685.77-49824597265040/netscaler_server.py; rm -rf "/home/kp/.ansible/tmp/ansible-tmp-1502997685.77-49824597265040/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_NcqxHM/ansible_module_netscaler_server.py", line 897, in <module>
    main()
  File "/tmp/ansible_NcqxHM/ansible_module_netscaler_server.py", line 788, in main
    session_login = session.login()
  File "/tmp/ansible_NcqxHM/ansible_module_netscaler_server.py", line 559, in login
    login = session.post(url, json=body, headers=self.headers, verify=self.verify)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='*.*.*.*', port=443): Max retries exceeded with url: /nitro/v1/config/login (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')],)",),))

failed: [*.*.*.*] (item={u'comment': u'Test Server', u'ip_address': u'*.*.*.*', u'name': u'kp-api-2'}) => {
    "failed": true,
    "item": {
        "comment": "Test Server",
        "ip_address": "*.*.*.*",
        "name": "kp-api-2"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_NcqxHM/ansible_module_netscaler_server.py\", line 897, in <module>\n    main()\n  File \"/tmp/ansible_NcqxHM/ansible_module_netscaler_server.py\", line 788, in main\n    session_login = session.login()\n  File \"/tmp/ansible_NcqxHM/ansible_module_netscaler_server.py\", line 559, in login\n    login = session.post(url, json=body, headers=self.headers, verify=self.verify)\n  File \"/usr/local/lib/python2.7/dist-packages/requests/sessions.py\", line 555, in post\n    return self.request('POST', url, data=data, json=json, **kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/requests/sessions.py\", line 508, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/requests/sessions.py\", line 618, in send\n    r = adapter.send(request, **kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/requests/adapters.py\", line 506, in send\n    raise SSLError(e, request=request)\nrequests.exceptions.SSLError: HTTPSConnectionPool(host='*.*.*.*', port=443): Max retries exceeded with url: /nitro/v1/config/login (Caused by SSLError(SSLError(\"bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')],)\",),))\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}

```

**Comment by jmcgill298** [comment]
@anendlesswaltz inventory_hostname is what you put under the group_vars in the inventory file

```
[netscaler]
netscaler_lb01
```
In this example, "{{ inventory_hostname }}" would equate to "netscaler_lb01"

You might do something like this:
```
[all:vars]
username=root
password=password

[netscaler]
netscaler_lb01 ansible_host=10.10.10.10
netscaler_lb02 ansible_host=10.10.11.10
```
In this example, "{{ inventory_hostname }}" would equate to "netscaler_lb01" and "netscaler_lb02", and "{{ ansible_host }}" woudl equate to "10.10.10.10" and "10.10.10.11" respectively. This allows you to use the friendly name when that is needed (an example would be creating a directory or file with the device's hostname), but use the IP address for establishing connections.
